//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabourDivider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public virtual System.DateTime From { get; set; }
        public virtual System.DateTime To { get; set; }
        public int JobId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
